# Rasterise pixel fonts (Google Fonts, OFL) into a compact JS glyph atlas: src/snap/fontdata.js
# Usage: python3 tools/make-font.py [ttf_cache_dir]   (downloads the TTFs if they are not cached)
import os, sys, base64, json, urllib.request, re
from PIL import Image, ImageDraw, ImageFont
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cache = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, 'dist', '.fonts')
os.makedirs(cache, exist_ok=True)
FONTS = {  # id: (Google family, px size)
    'body': ('Pixelify Sans', 16),
    'title': ('Jersey 10', 20),
    'small': ('Silkscreen', 8),
}
CHARS = [chr(c) for c in range(32, 127)] + list('éÉ×…’“”—·°♀♂')

def ttf(family):
    fn = os.path.join(cache, family.replace(' ', '+') + '.ttf')
    if not os.path.exists(fn):
        css = urllib.request.urlopen(urllib.request.Request('https://fonts.googleapis.com/css2?family=' + family.replace(' ', '+'), headers={'User-Agent': 'Wget/1.0'})).read().decode()
        url = re.search(r'url\((https://[^)]+\.ttf)\)', css).group(1)
        open(fn, 'wb').write(urllib.request.urlopen(url).read())
    return fn

out = {}
for fid, (family, size) in FONTS.items():
    f = ImageFont.truetype(ttf(family), size)
    asc, desc = f.getmetrics()
    glyphs = {}
    for ch in CHARS:
        try:
            adv = round(f.getlength(ch))
        except Exception:
            continue
        im = Image.new('L', (size * 3, asc + desc + 8), 0)
        d = ImageDraw.Draw(im); d.fontmode = '1'
        d.text((size, 4), ch, font=f, fill=255)
        bb = im.getbbox()
        if not bb:
            glyphs[ord(ch)] = [adv, 0, 0, 0, 0, '']
            continue
        x0, y0, x1, y1 = bb
        w, h = x1 - x0, y1 - y0
        bits = bytearray((w * h + 7) // 8)
        px = im.load()
        for y in range(h):
            for x in range(w):
                if px[x0 + x, y0 + y] > 127:
                    k = y * w + x
                    bits[k >> 3] |= 1 << (k & 7)
        glyphs[ord(ch)] = [adv, w, h, x0 - size, y0 - 4, base64.b64encode(bytes(bits)).decode()]
    # tofu check: glyphs identical to the notdef box are dropped
    out[fid] = {'asc': asc, 'desc': desc, 'size': size, 'g': glyphs}
    print(fid, family, size, 'asc', asc, 'desc', desc, len(glyphs), 'glyphs')

js = '/* Generated by tools/make-font.py from OFL Google Fonts (Pixelify Sans, Jersey 10, Silkscreen). */\nconst FONTDATA = ' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(root, 'src', 'snap', 'fontdata.js'), 'w').write(js)
print('fontdata.js', len(js) // 1024, 'KB')
